import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import SessionProvider from './providers/SessionProvider'
import "./globals.css";
import Header from "./components/header/Header";
import { ThemeProviderContainer } from "./providers/ThemeProvider";
import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
  title: "Asteroids App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen" id="modal-root">
        <SessionProvider session={session}>
          <ThemeProviderContainer>
            <Header />
            {children}
            <Footer />
          </ThemeProviderContainer>
        </SessionProvider>
      </body>
    </html>
  );
}
